baseURL = 'https://kpassa.me/'
languageCode = 'en-us'
title = 'kpassa.me'
theme = 'paper'

[params]
    twitter = "kpassapk"
    github = "kpassapk"
    instagram = "kpassapk"
    mastodon = "https://techhub.social/@kpassapk"
    rss = true

    avatar = 'kyle.passarelli@gmail.com'
    name = 'Kyle S Passarelli'
    bio = '''
Clojure developer. Co-founder, unifica.ai.

Available for consulting work!
'''

  # giscus
[params.giscus]
  repo = 'kpassapk/blog'                 # see https://giscus.app for more details
  repoId = 'R_kgDOHVttpQ'
  category = 'Q&A'
  categoryId = 'DIC_kwDOHVttpc4CaxV_'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'
